[project]
name = "sc_async_client"
requires-python = ">=3.8"

[tool.ruff]
line-length = 100
target-version = "py38"
fix = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
minversion = "7.0"
addopts = "-ra -q"
testpaths = [
    "tests"
]
filterwarnings = [
    "error",
    "ignore::DeprecationWarning"
]
pythonpath = [".", "src"]
